"""create intake queue and source ledger

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_job_claim", "agent_jobs", ["state", "available_at", "lease_until"], unique=False
    )
    op.create_table(
        "evaluation_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("logical_key", sa.String(length=64), nullable=False),
        sa.Column("company_code", sa.String(length=64), nullable=False),
        sa.Column("officer_code", sa.String(length=64), nullable=False),
        sa.Column("document_type", sa.String(length=40), nullable=False),
        sa.Column("period_start", sa.String(length=10), nullable=False),
        sa.Column("period_end", sa.String(length=10), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("latest_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("logical_key"),
    )
    op.create_table(
        "source_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=200), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["evaluation_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "version", name="uq_batch_version"),
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("delivery_key", sa.String(length=150), nullable=False),
        sa.Column("company_code", sa.String(length=64), nullable=False),
        sa.Column("officer_code", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("file_id", sa.Text(), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("declared_size", sa.Integer(), nullable=True),
        sa.Column("object_key", sa.String(length=200), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("source_file_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_key"),
    )
    op.create_index(op.f("ix_receipts_company_code"), "receipts", ["company_code"], unique=False)
    op.create_index(op.f("ix_receipts_sha256"), "receipts", ["sha256"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_receipt_id"), "audit_events", ["receipt_id"], unique=False
    )
    op.create_table(
        "source_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("locator", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_id", "locator", name="uq_receipt_locator"),
    )
    op.create_index(
        op.f("ix_source_records_receipt_id"), "source_records", ["receipt_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_records_receipt_id"), table_name="source_records")
    op.drop_table("source_records")
    op.drop_index(op.f("ix_audit_events_receipt_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_receipts_sha256"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_company_code"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_table("source_files")
    op.drop_table("evaluation_batches")
    op.drop_index("ix_job_claim", table_name="agent_jobs")
    op.drop_table("agent_jobs")
    # ### end Alembic commands ###
