"""acceptance_code_artifacts

Revision ID: a3abf32246ec
Revises: 438e64fe6510
"""

import sqlalchemy as sa
from alembic import op

revision = "a3abf32246ec"
down_revision = "438e64fe6510"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acceptance_artifacts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("media_type", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("acceptance_artifacts")
    # ### end Alembic commands ###
